#!/bin/bash
N=$(grep -n "#include" "$1" | tail -n 1 | cut -d : -f 1)
[ -n "$N" ] || N=0
while sed -ne "$(($N+1))p" "$1" | grep -q "^#endif"
do
  N=$(($N + 1))
done
head -n $N "$1"
echo "#include <ddekit/timer.h>"
tail -n +$(($N+1)) "$1"
