#!/bin/sh

# Cross compile a GNU build environment.

# Copyright (C) 2006, 2007, 2008, 2010 Free Software Foundation, Inc.

# Written by Thomas Schwinge <tschwinge@gnu.org>.

# This file is part of the GNU Hurd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# See <http://www.gnu.org/software/hurd/hurd/building/cross-compiling.html> for
# usage information.


# Functions from Paul Jarc's prjlibs available at
# <http://code.dogmap.org/prjlibs/>.

# sh/set.sh
case $? in 0) :;; *) (exit "$?");; esac &&
prj_set() {
  eval "$1=\${2?}"
}

# sh/set_default.sh
case $? in 0) :;; *) (exit "$?");; esac &&
prj_set_default() {
  : "${2?}" &&
  eval "
  if test \"\${$1+x}\" = x; then :; else
    $1=\$2
  fi"
}

# sh/unset.sh
case $? in 0) :;; *) (exit "$?");; esac &&
prj_unset() {
  while test "$#" != 0; do
    { eval "$1=" &&
      unset "$1" &&
      shift
    } || return "$?"
  done
}

# sh/x2.sh
case $? in 0) :;; *) (exit "$?");; esac &&
prj_x2() {
  : "${2?}" &&
  "$@" &&
  export "$2"
}

case $? in 0) :;; *) (exit "$?");; esac &&


# Create a clean environment.

prj_x2 prj_set LC_ALL C &&
prj_unset ASFLAGS CFLAGS CPPFLAGS CXXFLAGS LDFLAGS &&
prj_unset MAKEFLAGS &&


# Environment variables.

# `$ROOT' defaults to `~/tmp/gnu'.
prj_x2 prj_set_default ROOT ~/tmp/gnu &&
# `$ROOT' must specify an absolute path.
case $ROOT in
  /*)
    :;;
  *)
    ROOT=`cd "$ROOT" && pwd`;;
esac &&

prj_x2 prj_set_default SYS_ROOT "$ROOT"/sys_root &&

prj_x2 prj_set_default TARGET i586-pc-gnu &&

prj_x2 prj_set_default BINUTILS_SRC "$ROOT"/src/binutils &&
prj_x2 prj_set_default GCC_SRC "$ROOT"/src/gcc &&
prj_x2 prj_set_default GDB_SRC "$ROOT"/src/gdb &&
prj_x2 prj_set_default GLIBC_SRC "$ROOT"/src/glibc &&
prj_x2 prj_set_default GNUMACH_SRC "$ROOT"/src/gnumach &&
prj_x2 prj_set_default HURD_SRC "$ROOT"/src/hurd &&
prj_x2 prj_set_default MIG_SRC "$ROOT"/src/mig &&

# TODO.  See cross-gnu.
prj_x2 prj_set_default CROSS_GNU_REINSTALL_GLIBC y &&

prj_x2 prj_set PATH "$ROOT"/bin:"$PATH" &&

if gmake --version 2> /dev/null | grep -q GNU
then prj_x2 prj_set MAKE gmake
else prj_x2 prj_set MAKE make
fi

# See GNU Mach's `Makefile.am' for why.  This is for the packages that don't
# handle it themselves.
prj_x2 prj_set INSTALL "$GNUMACH_SRC"/build-aux/install-sh\ -C
