#!/bin/sh

set -x

{ [ x"$MACHINE" != x ] \
  || read MACHINE; } &&
. machines/"$MACHINE" &&

tmpdir=$(mktemp -d) &&

TARGET_MOUNT=$tmpdir/target &&
mkdir "$TARGET_MOUNT" &&

{ [ x"$TARGET" != x ] \
  || read TARGET; } &&

# See <http://bugs.debian.org/471528>.
sudo mkfs.ext2 -F -o hurd -I 128 -b 4096 "$TARGET" &&

sudo mount -t ext2 "$TARGET" "$TARGET_MOUNT" &&

case $SITE in
  bddebian)
    # flubber
    http_proxy=http://192.168.10.50:8123/;;
esac &&

if [ x${http_proxy+set} = xset ] \
   && [ x${no_use_http_proxy+set} != xset ]; then
  env_http_proxy="env http_proxy=$http_proxy"
fi &&
sudo \
  $env_http_proxy \
  /usr/share/crosshurd/makehurddir.sh "$TARGET_MOUNT" i486 gnu &&
unset env_http_proxy &&

# We have our own /etc/fstab.
sudo sed -i \
  -e s%/etc/fstab%/dev/null%g \
  "$TARGET_MOUNT"/native-install &&

sudo dd of="$TARGET_MOUNT"/install <<EOF_INSTALL &&
#!/bin/sh

set -x &&

export TERM &&
TERM=mach &&

umask 022 &&

# Needed for dpkg.
{ test -c /servers/socket/1 \
  || settrans -c /servers/socket/1 /hurd/pflocal; } &&

# Do not configure debconf, only unpack it.
dpkg --unpack --force-depends /var/cache/apt/archives/debconf_*.deb &&

debconf-set-selections <<EOS &&
ca-certificates	ca-certificates/trust_new_crts	select	yes
adduser	adduser/homedir-permission	boolean	true
dash	dash/sh	boolean	true
debconf	debconf/frontend	select	Dialog
debconf	debconf/priority	select	medium
tcpd	tcpd/paranoid-mode	boolean	false
libpam-runtime	libpam-runtime/override	boolean	false
libpam-runtime	libpam-runtime/profiles	multiselect	unix, gnome-keyring, consolekit
libpam-runtime	libpam-runtime/conflicts	error	
EOS

( cd /dev &&
  MAKEDEV $DISK_ROOT $DISK_SWAP $DISK_DATA $DISK_DATA_LOCAL $DISK_VAR
) &&

# Already enable swap up here.
mkswap.linux -v1 /dev/$DISK_SWAP &&
/hurd/mach-defpager &&
swapon -a &&

./native-install &&

passwd \
  -d root &&

if test -r /dev/random; then :; else
  cp /hurd/ext2fs.static /dev/random
fi &&
if test -r /dev/urandom; then :; else
  cp /hurd/ufs.static /dev/urandom
fi &&

settrans \
  -fcgap \
  /servers/socket/2 \
  /hurd/pfinet \
  -i eth0 -a $NET_IP_ADDRESS -g $NET_IP_GATEWAY -m $NET_IP_MASK
EOF_INSTALL

sudo chmod +x "$TARGET_MOUNT"/install &&

sudo dd of="$TARGET_MOUNT"/install-packages <<EOF_INSTALL_PACKAGES &&
#!/bin/sh

set -x

apt-get update &&

apt-get --purge -y --force-yes dist-upgrade &&


# Pre-configure some packages.

# For debconf-get-selections.
apt-get -y --force-yes install debconf-utils &&

debconf-get-selections > /tmp/debconf-selections &&

while read p q t v; do
  if grep -q '^[^	]*	'"\$q"'	' < /tmp/debconf-selections; then :; else
    debconf-set-selections <<EOS
\$p	\$q	\$t	\$v
EOS
  fi
done <<EOS &&
cvs	cvs/badrepositories	select	ignore
cvs	cvs/pserver	boolean	false
cvs	cvs/repositories	string	/var/lib/cvs
libpaper1	libpaper/defaultpaper	select	a4
locales	locales/default_environment_locale	select	None
locales	locales/locales_to_be_generated	multiselect	en_US.UTF-8 UTF-8
man-db	man-db/install-setuid	boolean	false
nullmailer	nullmailer/adminaddr	string	thomas@schwinge.name
nullmailer	nullmailer/relayhost	string	mail.schwinge.homeip.net qmqp
nullmailer	shared/mailname	string	$QUALIFIED_HOSTNAME
popularity-contest	popularity-contest/participate	boolean	true
tex-common	tex-common/managecache	boolean	false
x-ttcidfont-conf	x-ttcidfont-conf/tt_backend	select	freetype
EOS


# Install packages.

packages='
  autoconf
  autoconf-doc
  automake
  bash-doc
  binutils-doc
  build-essential
  dpkg-dev
  libtool
  libtool-doc
  make-doc
  g++-4.4
  gcc-4.4-doc
  cpp-4.4-doc
  gdb
  gdb-doc
  hurd-dbg
  libc0.3-dbg
  glibc-doc
  glibc-doc-reference
  manpages-dev
  mig
  bzr bzr-doc
  cvs
  darcs
  git
  subversion
  gnu-standards
  bc
  bzip2
  devscripts
  joe
  fakeroot
  file
  info
  less
  locales
  lynx
  man
  manpages
  netcat
  nullmailer
  pkg-config
  popularity-contest
  rsync
  screen
  sudo
  ssh
  texinfo
  time
  w3m
  wdiff
  wget
' &&

# dsyslog doesn't install / configure properly, but nullmailer (weakly) depends
# on it.
packages=\$packages'
  dsyslog-
' &&

# System instability issues.
packages=\$packages'
  system-log-daemon-
  syslog-ng-
  socklog-run-
  inetutils-syslogd-
  dsyslog-
' &&

# emacs (emacs23) isn't installable yet.
# In fact, no emacs version's packages are installable at the moment...
#packages=\$packages'
#  emacs-
#  emacs22
#' &&

apt-get -y --force-yes install \$packages &&


apt-get build-dep \
  libc0.3 \
  gdb \
  gnumach \
  hurd &&


# Configure packages.

if grep '^%sudo' /etc/sudoers; then :; else
  cat >> /etc/sudoers
fi <<"EOS" &&

%sudo	ALL=(ALL) ALL
EOS

# TODO: should soon be fixed; patch has been posted to bug-hurd IIRC.
{ ed /etc/ssh/sshd_config || :; } <<"EOC"
/^UsePrivilegeSeparation/
s/yes/no/
w
EOC
EOF_INSTALL_PACKAGES

sudo chmod +x "$TARGET_MOUNT"/install-packages &&


sudo dd of="$TARGET_MOUNT"/etc/hostname <<EOF &&
$QUALIFIED_HOSTNAME
EOF

h=$(expr "$QUALIFIED_HOSTNAME" : '\([^\.]*\)') &&
sudo dd of="$TARGET_MOUNT"/etc/hosts <<EOF &&
$NET_IP_ADDRESS	$QUALIFIED_HOSTNAME $h 

127.0.0.1	localhost

::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
ff02::3	ip6-allhosts
EOF
unset h &&


sudo dd of="$TARGET_MOUNT"/etc/fstab <<EOF &&
/dev/$DISK_ROOT / ext2 rw 1 1
/dev/$DISK_SWAP none swap sw 0 0
EOF
if [ x${DISK_DATA+set} = xset ]; then
  sudo mkdir -p "$TARGET_MOUNT"/media/data &&
  sudo dd of="$TARGET_MOUNT"/etc/fstab conv=notrunc oflag=append <<EOF
/dev/$DISK_DATA /media/data ext2 rw 1 2
EOF
fi &&
if [ x${DISK_DATA_LOCAL+set} = xset ]; then
  sudo mkdir -p "$TARGET_MOUNT"/media/data-local &&
  sudo dd of="$TARGET_MOUNT"/etc/fstab conv=notrunc oflag=append <<EOF
/dev/$DISK_DATA_LOCAL /media/data-local ext2 rw 1 2
EOF
fi &&
if [ x${DISK_VAR+set} = xset ]; then
  sudo mkdir -p "$TARGET_MOUNT"/media/var &&
  sudo dd of="$TARGET_MOUNT"/etc/fstab conv=notrunc oflag=append <<EOF
/dev/$DISK_VAR /media/var ext2 rw 1 2
EOF
fi &&


sudo ln -sf /usr/share/zoneinfo/Etc/UTC "$TARGET_MOUNT"/etc/localtime &&


if [ x${http_proxy+set} = xset ]; then
  sudo dd of="$TARGET_MOUNT"/etc/apt/apt.conf <<EOF
Acquire::http::Proxy "$http_proxy";
EOF
fi &&


case $SITE in
  bddebian)
    mirror=.us;;
esac &&
sudo dd of="$TARGET_MOUNT"/etc/apt/sources.list <<EOF &&
deb http://ftp$mirror.debian.org/debian unstable main non-free
deb-src http://ftp$mirror.debian.org/debian unstable main non-free
#deb http://ftp$mirror.debian.org/debian experimental main non-free
#deb-src http://ftp$mirror.debian.org/debian experimental main non-free

deb http://ftp.debian-ports.org/debian unreleased main
deb-src http://ftp.debian-ports.org/debian unreleased main
EOF
unset mirror &&


: sudo umount "$TARGET_MOUNT" &&
: sudo rm -rf "$tmpdir"
