# Makefile for libchannel
#
#   Copyright (C) 2007 Free Software Foundation, Inc.
# 
#   Written by Carl Fredrik Hammar <hammy.lite@gmail.com>
#
#   This file is part of the GNU Hurd.
#
#   The GNU Hurd is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2, or (at
#   your option) any later version.
#
#   The GNU Hurd is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111, USA.

dir := libchannel
makemode := library

libname := libchannel
installhdrs := channel.h

SRCS = channel.c
LCLHDRS := channel.h

OBJS = $(SRCS:.c=.o)

include ../Makeconf
